<?php

use Zend\Form\Element\Submit;

$title = "Adicionando fornecedor";
$this->headTitle($title);
?>

<h1><?=$this->escapeHtml($title)?></h1>

<?php
$form->setAttribute('action', $this->url('fornecedor', ['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$nome = $this->form->get('nome')->setAttribute('class','form-control')->setAttribute('autofocus','autofocus');
$sobrenome = $this->form->get('sobrenome')->setAttribute('class','form-control');
$email = $this->form->get('email')->setAttribute('class','form-control');
$situacao = $this->form->get('situacao')->setAttribute('class','form-control');
$submit = $this->form->get('submit')->setAttribute('class','btn btn-primary btn-lg');
?>

<?=$this->formElement($id)?>
<div class = "form-group">
    <div class = "col-md-6">
        <?=$this->formLabel($nome)?>
        <?=$this->formElement($nome)?>
        <?=$this->formElementErrors()->render($nome, ['class' => 'help-block'])?>
    </div>
</div>
<div class = "form-group">
    <div class = "col-md-6">
        <?=$this->formLabel($sobrenome)?>
        <?=$this->formElement($sobrenome)?>
        <?=$this->formElementErrors()->render($sobrenome, ['class' => 'help-block'])?>
    </div>
</div>
<div class = "form-group">
    <div class = "col-md-8">
        <?=$this->formLabel($email)?>
        <?=$this->formElement($email)?>
        <?=$this->formElementErrors()->render($email, ['class' => 'help-block'])?>
    </div>
</div>
<div class = "form-group">
    <div class = "col-md-4">
        <?=$this->formLabel($situacao)?>
        <?=$this->formElement($situacao)?>
        <?=$this->formElementErrors()->render($situacao, ['class' => 'help-block'])?>
    </div>
</div>
<div class = "row">
    <?=$this->formElement($submit)?>
    <a href = "<?=$this->url('fornecedor', ['action'=>'index'])?>" class = "btn btn-warning">Voltar</a>
</div>
