<?php
$title = "Cardapio";
$this->headTitle($title);
?>
<script src="<?=$this->basePath('/js/cardapio.js')?>"></script>
<h1><?=$this->escapeHtml($title)?></h1>

<section class="content-header">
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">Cadastrar cardapio</button>
<div class="modal fade modal-xl" id="modal-default" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cardapio</h4>
            </div>
            <div class="modal-body">
                <?php
                    $form->setAttribute('action', $this->url('fornecedor', ['action' => 'cardapio']));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $id = $this->form->get('ID_ITEM_ITM');
                    $item = $this->form->get('ST_NOME_ITM')->setAttribute('class','form-control')->setAttribute('id','item');
                    $valor = $this->form->get('VL_ITEM_ITM')->setAttribute('class','form-control')->setAttribute('id','valor');
                    $titulo = $this->form->get('ST_TITULO_TIT')->setAttribute('class','form-control ')->setAttribute('autofocus','autofocus');
                ?>
                <div class="container" >
                    <div id="container">
                        <div class="row">
                            <div class="col-sm-6">
                                <?=$this->formLabel($titulo)?>
                                <?=$this->formElement($titulo)?>
                            </div>
                        </div>
                        <div id="tituloItens" class="row" style="display:none; " >
                            <div class="col-sm-4">
                                <?=$this->formLabel($item)?>
                            </div>
                            <div class="col-sm-2">
                                <?=$this->formLabel($valor)?>
                            </div>
                        </div>
                        <div class="row" id="itens" style="display:none">
                            <div class="col-sm-4">
                                <?=$this->formElement($item)?>
                            </div>
                            <div class="col-sm-1">
                                <?=$this->formElement($valor)?>
                            </div>
                            <div class="col-sm-1">
                                <button type="button" id="exclsuirItens" name="itemExcluido"class="btn btn-block btn-danger btn-xs" onclick="deletarItens('itens')" >Exluir  </button>
                            </div>
                        </div>
                    </div> 
                    <div class="row" style="margin-top: 1%">
                            <div class="col-sm-2">
                                <button type="button" id="adicionarItens" class="btn btn-block btn-info btn-xs" > Adicionar item </button>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                <button id="salvar" type="button" class="btn btn-primary">Salvar</button>
                <!-- <button id="salvar" type="button" class="btn btn-primary">Salvar</button> -->
            </div>
        </div>
    </div>
</div>
</section>
<section class="content container-fluid">
    <div>
        <div class="col-md-12">
        <?php
            foreach($arTitulos as $titulo) :
        ?>
                    <div class="box box-default collapsed-box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=$titulo['ST_TITULO_TIT']?></h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            <button id='modalbody'type="button" class="btn btn-box-tool" onclick="editarItens('<?=$titulo['ID_TITULO_TIT']?>')" data-toggle="modal" data-target="#modal-default"><i class="glyphicon glyphicon-pencil"></i></button>
                        </div>
                    </div>  
                        <div class="box-body">
                            <table class="table no-border">
                            <tbody>
                                <?php                    
                                    $arItens = $tableItem->fetchAll()->toArray();
                                    foreach($arItens as $itens) :
                                        if($titulo['ID_TITULO_TIT'] == $itens['ID_TITULO_TIT']){
                                        ?>
                                            <tr>
                                            <th style="width: 5%"></th>
                                            <th style="width: 85%"><?=$itens['ST_NOME_ITM']?></th>
                                            <th><?=number_format($itens['VL_ITEM_ITM'],2,",",".")?></th>
                                            </tr>
                                        <?php
                                        }
                                    endforeach;
                                ?>
                                </tbody>
                            </table> 
                        </div> 
                    </div>
            <?php
            endforeach;
            ?>
        </div>
    </div>
</section>
